# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Self-hosted

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

   # Step 2: Install dependencies and build the project
- script: |
    npm install
    npm run build
  displayName: 'Install Dependencies and Build'

# Step 3: Run Tests
- script: |
    npm test
  displayName: 'Run Tests'

# Step 4: Publish test results 
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

# Step 5: Publish Build Artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Build Artifact'
